In [17]:
import numpy as np
np.__version__

'1.11.3'

In [3]:
np?

In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(L[0])

int

In [11]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
type(L2[0])

str

In [15]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.array([1, 3, 4, 5, 6], dtype="float32")

array([ 1.,  3.,  4.,  5.,  6.], dtype=float32)

In [20]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [21]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [24]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [26]:
np.random.random((3, 3))

array([[ 0.47533836,  0.31805047,  0.45414459],
       [ 0.63289495,  0.77736248,  0.74891723],
       [ 0.40488641,  0.36215594,  0.01162051]])

In [27]:
np.random.normal(0, 1, (3, 3))

array([[ 1.73001861, -1.33628318, -1.18947138],
       [ 0.45786189, -0.9745402 , -1.57183725],
       [ 0.78402115,  1.98621977,  0.75107218]])

In [28]:
np.random.randint(0, 10, (3, 3))

array([[7, 7, 2],
       [1, 6, 2],
       [5, 8, 9]])

In [29]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [30]:
np.empty(3)

array([ 1.,  1.,  1.])